# Generated by Django 4.1.2 on 2022-10-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_category_product_image_product_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("cart", models.CharField(default="", max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="desc",
            field=models.CharField(max_length=600),
        ),
    ]
